- force-app/main/default/layouts/Dog__c-Dog Layout.layout-meta.xml
- force-app/main/default/objects/BackgroundCheck__c/BackgroundCheck__c.object-meta.xml
- force-app/main/default/objects/DogRelationship__c/DogRelationship__c.object-meta.xml
- force-app/main/default/objects/DogRelationship__c/fields/Type__c.field-meta.xml
Make Dog Relationship type multi-select
Changed DogRelationShip and BackgroundCheck name fields to auto number
#72
> Make Dog Relationship type multi-select

- force-app/main/default/objects/Contact/Contact.object-meta.xml
Changed new contact button to default.
Fixes #78
> Use default edit rather than npsp RD2_EntryForm

- force-app/main/default/layouts/BackgroundCheck__c-Background Check Layout.layout-meta.xml
- force-app/main/default/layouts/DogRelationship__c-Dog Relationship Layout.layout-meta.xml
> changing Required to Readonly to resolve error

- datasets/recipes/program_assignment.recipe.yml
- force-app/main/default/globalValueSets/Programs.globalValueSet-meta.xml
> Add Sweet Snoopers Trainer to program

- datasets/recipes/contact.recipe.yml
- datasets/recipes/lead.recipe.yml
- force-app/main/default/globalValueSets/LeadInterest.globalValueSet-meta.xml
Added value to global picklist.  Added value to fakery recipe.
#92
> Added 'Assistance Dogs Set in Motion Program' to LeadInterest

- datasets/recipes/CEU.recipe.yml
- force-app/main/default/objects/ContinuingEducationUnit__c/fields/Authority__c.field-meta.xml
- force-app/main/default/permissionsets/AtlasSuperUser.permissionset-meta.xml
Update fakery recipe and AtlasSuperUser permission set
#106
> Add CEU Authority Other option

- datasets/recipes/program_assignment.recipe.yml
- force-app/main/default/objects/ProgramAssignment__c/ProgramAssignment__c.object-meta.xml
Add ExpectedCompletion to snowfakery recipe
Fixes #93
> Re-order ProgramAssignment search list view

- datasets/mapping.yml
- datasets/recipes/log.recipe.yml
- force-app/main/default/layouts/Contact-Atlas Contact Layout.layout-meta.xml
- force-app/main/default/layouts/Log__c-Client Log Layout.layout-meta.xml
- force-app/main/default/layouts/Log__c-Facilitator Log Layout.layout-meta.xml
- force-app/main/default/objects/Log__c/Log__c.object-meta.xml
Update Log layout and Atlas Contact layout
#123
> Change Log Name to auto filled field

- datasets/recipes/common.recipe.yml
- force-app/main/default/flexipages/Dog_Record_Page.flexipage-meta.xml
- force-app/main/default/globalValueSets/Positions.globalValueSet-meta.xml
Replace with just Client
Remove fields from layout.
#90
> Remove Teams Set in Motion Client

- force-app/main/default/objects/BackgroundCheck__c/fields/Date__c.field-meta.xml
Changed label for Date__c to just Date
#153
> Change label for Date field

- force-app/main/default/globalValueSets/Programs.globalValueSet-meta.xml
- force-app/main/default/lwc/fileUploadCmp/fileUploadCmp.css
- force-app/main/default/lwc/fileUploadCmp/fileUploadCmp.html
- force-app/main/default/lwc/relatedObjectCmp/relatedObjectCmp.css
- force-app/main/default/lwc/relatedObjectCmp/relatedObjectCmp.html
- force-app/main/default/objects/ContentVersion/fields/Category__c.field-meta.xml
- force-app/main/default/objects/ContentVersion/fields/Type__c.field-meta.xml
- force-app/main/default/objects/ProgramAssignment__c/fields/Contact__c.field-meta.xml
Changed header to related list for Programs
Added bottom border to related objects.  Not perfect (radius is still there), but much better.
#177
> Add value to Programs

- cumulusci.yml
- force-app/main/default/lwc/logFormCmp/logFormCmp.html
- force-app/main/default/lwc/logFormCmp/logFormCmp.js
- force-app/main/default/objects/Log__c/fields/ClientHours__c.field-meta.xml
- force-app/main/default/objects/Log__c/fields/Client__c.field-meta.xml
- force-app/main/default/objects/Log__c/fields/Date__c.field-meta.xml
- force-app/main/default/objects/Log__c/fields/Dog__c.field-meta.xml
- force-app/main/default/objects/Log__c/fields/OtherHours__c.field-meta.xml
- force-app/main/default/objects/Log__c/fields/PublicAccessHours__c.field-meta.xml
- force-app/main/default/objects/Log__c/fields/Satisfaction__c.field-meta.xml
- force-app/main/default/objects/Log__c/fields/SessionType__c.field-meta.xml
- force-app/main/default/objects/Log__c/fields/Submitter__c.field-meta.xml
- force-app/main/default/permissionsets/AtlasSuperUser.permissionset-meta.xml
- force-app/main/test/TestLogController.cls
- force-app/main/test/TestReminders.cls
- scratch-config/main/default/profiles/Admin.profile-meta.xml
Made fields required and added missing fields to form.
#158
> Make log form closer to web form

- force-app/main/default/layouts/Contact-Atlas Contact Layout.layout-meta.xml
- force-app/main/default/objects/npe4__Relationship__c/fields/npe4__Type__c.field-meta.xml
> Deactivate relationship types

- cumulusci.yml
- force-app/main/default/flexipages/DogRecordPage.flexipage-meta.xml
- force-app/main/default/permissionsets/AtlasSuperUser.permissionset-meta.xml
- scratch-config/main/default/profiles/Admin.profile-meta.xml
Fixed AtlasSuperUser permission set.
Added Last received dates to Other tab of Dog layout
#209
> Added last dates for Dog files

- force-app/main/default/triggers/ContactTrigger.trigger
- force-app/main/default/triggers/ContactTrigger.trigger-meta.xml
- force-app/main/default/triggers/ProgramAssignmentTrigger.trigger
- force-app/main/test/TestContactTrigger.cls
- force-app/main/test/TestContactTrigger.cls-meta.xml
Added trigger to update npe01__HomeEmail__c when Email changes
Fixes #225
> 225 trigger to populate npe01  homeemail  c

- config/Program__c.json
- config/project-scratch-def.json
- force-app/main/default/globalValueSets/Language.globalValueSet-meta.xml
- force-app/main/default/lwc/newContactCmp/newContactCmp.html
- force-app/main/default/lwc/newContactCmp/newContactCmp.js
- force-app/main/default/objects/Team__c/fields/Client__c.field-meta.xml
- force-app/main/default/objects/Team__c/fields/Dog__c.field-meta.xml
- force-app/main/default/permissionsets/AtlasSuperUser.permissionset-meta.xml
- force-app/main/default/settings/Name.settings-meta.xml
- orgs/dev.json
- scratch-config/main/default/profiles/Admin.profile-meta.xml
Updated fields for Team so Client and Dog are required.  Use Name field for contact.  Split out "Chinese" languages.
#234 #233
> 233 new contact form

- force-app/main/default/layouts/Contact-Atlas Contact Layout.layout-meta.xml
- force-app/main/default/objects/Contact/fields/FacilitatorCertificationValidUntil__c.field-meta.xml
Change FacilitatorCertificationValidUntil to a formula field.
#264
> Change FacilitatorCertificationValidUntil

- force-app/main/default/globalValueSets/Stress.globalValueSet-meta.xml
Removed default from Stress picklest
#269
> Remove default value from Stress picklist

- force-app/main/default/lwc/newLeadCmp/newLeadCmp.html
- force-app/main/default/lwc/newLeadCmp/newLeadCmp.js
Corrected check for Specified pronoun, and used reference for interest field.
#274
> Fixed pronoun-other and LeadInterest

- force-app/main/default/lwc/newLeadCmp/newLeadCmp.html
- force-app/main/default/lwc/newLeadCmp/newLeadCmp.js
- unpackaged/pre/main/default/objects/npe4__Relationship__c/fields/npe4__Type__c.field-meta.xml
> 275 update relationshiptype in dev

- force-app/main/default/globalValueSets/LeadInterest.globalValueSet-meta.xml
Added Puppy Raising and Standalone Specialty Courses to Lead Interest.
Fixes #282
> Add values to Lead Interest

- force-app/main/default/globalValueSets/Language.globalValueSet-meta.xml
- force-app/main/default/objects/Contact/fields/LeadSourceOther__c.field-meta.xml
- force-app/main/default/objects/Contact/fields/PronounOther__c.field-meta.xml
- force-app/main/default/objects/Contact/fields/SpecifiedAbilityAccommodation__c.field-meta.xml
- force-app/main/default/objects/Contact/fields/SpecifiedAbilityStatus__c.field-meta.xml
- force-app/main/default/objects/Contact/fields/SpecifiedGenderIdentity__c.field-meta.xml
- force-app/main/default/objects/Contact/fields/SpecifiedRaceEthnicity__c.field-meta.xml
- force-app/main/default/objects/Contact/fields/SpecifiedSexualOrientation__c.field-meta.xml
- force-app/main/default/objects/Contact/fields/SpecifiedVeteranStatus__c.field-meta.xml
- force-app/main/default/objects/ContinuingEducationUnit__c/fields/AuthorityOther__c.field-meta.xml
- force-app/main/default/objects/Dog__c/fields/Breed__c.field-meta.xml
- force-app/main/default/objects/Dog__c/fields/MicrochipNumber__c.field-meta.xml
- force-app/main/default/objects/Lead/fields/LeadSourceOther__c.field-meta.xml
- force-app/main/default/objects/Lead/fields/PronounOther__c.field-meta.xml
- force-app/main/default/objects/Log__c/fields/Handler__c.field-meta.xml
Change field length for Specified... fields to 128 characters.
Fixes #283
> Change text field lengths

- force-app/main/default/objects/Contact/fields/GenderIdentity__c.field-meta.xml
Make Gender Identity multi-select.
#291
> Make GenderIdentity a multi-select.

- force-app/main/default/flexipages/LeadRecordPage.flexipage-meta.xml
- force-app/main/default/layouts/Lead-Lead Layout.layout-meta.xml
Added notes to side bar on Lead Record Page.
Added Activity to side bar.
Moved duplicate check to bar above details.
> Lead layout tweaks

- force-app/main/default/layouts/Contact-Atlas Contact Layout.layout-meta.xml
- force-app/main/default/layouts/Lead-Lead Layout.layout-meta.xml
Add Campaign history related list to Lead and Contact
> Add Campaign history related lists

- force-app/main/default/classes/FileController.cls
Filtered Related Files to remove notes
fixes #302
> Remove notes from related files

- force-app/main/default/classes/FileService.cls
- force-app/main/default/layouts/Contact-Atlas Contact Layout.layout-meta.xml
- force-app/main/default/objects/ContentVersion/fields/Category__c.field-meta.xml
- force-app/main/default/objects/ContentVersion/fields/Type__c.field-meta.xml
Change TSiM to Standalone Programs in File type list
Remove Last TSiM file dates from Contact layout
#305
> Change TSiM to Standalone

- force-app/main/default/classes/FileController.cls
- force-app/main/default/lwc/relatedFilesCmp/relatedFilesCmp.js
Changed date in related files to date-local to match entered date.
Removed update to last* files because that is in the trigger now.
#296
> Show local date in related files

- force-app/main/default/objects/Contact/fields/Birthdate.field-meta.xml
Add help text to birthdate.
#314
> Add help text to birthdate

- force-app/main/default/flexipages/DogRecordPage.flexipage-meta.xml
- force-app/main/default/layouts/Dog__c-Dog Layout.layout-meta.xml
- force-app/main/default/lwc/newDogCmp/newDogCmp.html
- force-app/main/default/lwc/newDogCmp/newDogCmp.js
- force-app/main/default/objects/Dog__c/fields/Birthdate__c.field-meta.xml
Removed Expired and Activation date from form.
Corrected Birthdate so it will show in form.
Added help text in Birthdate.
#260
> 260 dog changes

- force-app/main/default/triggers/ContactTrigger.trigger
Changed Contact trigger from before update to after update
> 320 Client Last Application Received Date not being set in details

- force-app/main/default/lwc/backgroundCheckFormCmp/backgroundCheckFormCmp.js
- force-app/main/default/lwc/ceuFormCmp/ceuFormCmp.js
- force-app/main/default/lwc/fileUploadCmp/fileUploadCmp.js
- force-app/main/default/lwc/patFormCmp/patFormCmp.js
- force-app/main/default/lwc/puppyLogFormCmp/puppyLogFormCmp.js
Add mov, mp4, and zip file types (when missing) to:
- Background-check
- CEU
- File Upload
- PAT
- Puppy log
#342
> Added allowed file types

- force-app/main/default/classes/PuppyLog.cls
- force-app/main/default/classes/PuppyLogController.cls
- force-app/main/default/lwc/puppyLogFormCmp/puppyLogFormCmp.js
- force-app/main/default/lwc/relatedPuppyLogCmp/relatedPuppyLogCmp.js
- force-app/main/default/lwc/relatedPuppyLogsCmp/relatedPuppyLogsCmp.html
- force-app/main/default/lwc/relatedPuppyLogsCmp/relatedPuppyLogsCmp.js
- force-app/main/test/TestPuppyLogController.cls
- force-app/main/test/TestPuppyLogController.cls-meta.xml
Allow saving a record without a file attachment.
Remove use of message channel.
#344
> Simplify puppy log

- force-app/main/default/layouts/PuppyLog__c-Puppy Log Layout.layout-meta.xml
- force-app/main/default/lwc/relatedPuppyLogsCmp/relatedPuppyLogsCmp.js
Fix "request support" column
Add related files to the puppy log layout
#354
> Strip html from Puppy Log details

- force-app/main/default/classes/ContinuingEducationUnitController.cls
- force-app/main/default/layouts/ContinuingEducationUnit__c-CEU Layout.layout-meta.xml
- force-app/main/default/lwc/relatedBackgroundCheckCmp/relatedBackgroundCheckCmp.js
- force-app/main/default/lwc/relatedCeusCmp/relatedCeusCmp.js
- force-app/main/default/objects/ContinuingEducationUnit__c/ContinuingEducationUnit__c.object-meta.xml
- force-app/main/default/objects/ContinuingEducationUnit__c/listViews/All.listView-meta.xml
Added related files to CEU layout
Removed unused imports from relatedBackgroundCheckCmp
#355
> Add Name to CEU list and swap prog hours with requested CEUs

- force-app/main/default/lwc/logFormCmp/logFormCmp.js
- force-app/main/default/lwc/relatedBackgroundChecksCmp/relatedBackgroundChecksCmp.js
- force-app/main/default/lwc/relatedCeusCmp/relatedCeusCmp.js
- force-app/main/default/lwc/relatedFilesCmp/relatedFilesCmp.html
- force-app/main/default/lwc/relatedFilesCmp/relatedFilesCmp.js
- force-app/main/default/lwc/relatedLogsCmp/relatedLogsCmp.js
- force-app/main/default/lwc/relatedPatsCmp/relatedPatsCmp.html
- force-app/main/default/lwc/relatedPuppyLogsCmp/relatedPuppyLogsCmp.html
Resolved
Fixed error when attempting to create a log without required fields.
> Salesforce suddenly started throwing exceptions on these

- force-app/main/default/lwc/backgroundCheckFormCmp/backgroundCheckFormCmp.html
- force-app/main/default/lwc/backgroundCheckFormCmp/backgroundCheckFormCmp.js
- force-app/main/default/lwc/ceuFormCmp/ceuFormCmp.js
- force-app/main/default/lwc/patFormCmp/patFormCmp.js
Background-checks
CEUs
PATs
Show local date in related PATs list
> Remove requirement for attached flles

- force-app/main/default/lwc/contactStatusCmp/contactStatusCmp.html
Changed the class to allow wrapping in the grid.
Fixes #347
> Wrap contact status indicators

- force-app/main/default/classes/FileService.cls
- scripts/python/generate_file_code/category.py
- scripts/python/generate_file_code/contact.py
- scripts/python/generate_file_code/dog.py
- scripts/python/generate_file_code/templates/update.py
Update python scripts to put all fields in the query. This will prevent added categories or types in production from causing problems.
> When updating the last date, select all known fields

- force-app/main/default/lwc/relatedFilesCmp/relatedFilesCmp.js
File sort was trying to use an undefined property.
> Fix file sort

- force-app/main/default/objects/Dog__c/fields/ExpiryDateStatus__c.field-meta.xml
- force-app/main/default/objects/Dog__c/fields/HealthCareRecordsStatus__c.field-meta.xml
Modified Dog Health Care Record Status to show N/A if the dog status is None
> Show N/A for health status if dog status is None

- force-app/main/default/lwc/relatedPatsCmp/relatedPatsCmp.js
Fixed delete in Related PATs
#393
> Fix delete PAT in related pats

- force-app/main/default/classes/DogController.cls
- force-app/main/default/triggers/TeamTrigger.trigger
- force-app/main/default/triggers/TeamTrigger.trigger-meta.xml
- force-app/main/test/TestTeamTrigger.cls
- force-app/main/test/TestTeamTrigger.cls-meta.xml
Created trigger on Team create and update to create a Client dog relationship between the Client and Dog.
#403
> Add trigger to Team to create dog relationship

- force-app/main/default/lwc/relatedFilesCmp/relatedFilesCmp.js
- force-app/main/default/messageChannel/ceuForm.messageChannel-meta.xml
- force-app/main/default/messageChannel/logForm.messageChannel-meta.xml
- force-app/main/default/messageChannel/patForm.messageChannel-meta.xml
- force-app/main/default/messageChannel/puppyLogForm.messageChannel-meta.xml
- force-app/main/default/messageChannel/updateFile.messageChannel-meta.xml
Restore message channels so we can build the package
Some code cleanup.
> Clean up relatedFiles cmp a bit

- force-app/main/default/objects/Contact/fields/Language__c.field-meta.xml
Set default preferred language to English
Fixes #423
> Set contact default language

- force-app/main/default/objects/ProgramAssignment__c/ProgramAssignment__c.object-meta.xml
- force-app/main/default/objects/ProgramAssignment__c/listViews/All.listView-meta.xml
Added TA Requested to list views for Program Assignment
> Add TA Requested to list views

- force-app/main/default/layouts/Contact-Atlas Contact Layout.layout-meta.xml
- force-app/main/default/objects/Contact/fields/Age__c.field-meta.xml
- force-app/main/default/permissionsets/AtlasSuperUser.permissionset-meta.xml
Added Age as a derived field to contact
#435
> 435 add age as a derived field in contact

- force-app/main/default/classes/PostInstall.cls
- force-app/main/test/TestPostInstall.cls
Added post-install processing to link dog and client documents to their teams.
> Post install

- force-app/main/default/classes/PublicAccessTestController.cls
- force-app/main/default/lwc/relatedPatsCmp/relatedPatsCmp.js
- force-app/main/test/TestPublicAccessTestController.cls
Added ValidUntil to related PAT list
> Added ValidUntil to related PAT list

- force-app/main/default/classes/TeamController.cls
- force-app/main/default/layouts/Contact-Atlas Contact Layout.layout-meta.xml
- force-app/main/default/layouts/DogRelationship__c-Dog Relationship Layout.layout-meta.xml
- force-app/main/default/lwc/relatedTeamsCmp/relatedTeamsCmp.js
- force-app/main/default/lwc/teamFormCmp/teamFormCmp.html
- force-app/main/default/lwc/teamFormCmp/teamFormCmp.js
- force-app/main/default/objects/DogRelationship__c/fields/DogStatus__c.field-meta.xml
- force-app/main/default/permissionsets/AtlasSuperUser.permissionset-meta.xml
- force-app/main/test/TestTeamController.cls
- scratch-config/main/default/profiles/Admin.profile-meta.xml
Added Team Status to RelatedTeams list and to Edit Team form.
Added DogStatus to DogRelationship and Contact layout.
> 444 teams dog status columns

- force-app/main/default/classes/FileService.cls
- force-app/main/default/objects/Contact/fields/BoardTermValidUntil__c.field-meta.xml
- force-app/main/default/objects/Contact/fields/LastBoardTermStartDate__c.field-meta.xml
- force-app/main/default/permissionsets/AtlasSuperUser.permissionset-meta.xml
- force-app/main/default/quickActions/Contact.Board.quickAction-meta.xml
- force-app/main/default/triggers/ContactTrigger.trigger
- force-app/main/test/TestContactTrigger.cls
- scratch-config/main/default/profiles/Admin.profile-meta.xml
1. Add Contact.LastBoardTermStartDateAdd Trigger to set BoardTermValidUntil
2. Add new field to Board specific settings
3. Add new field to AtlasSuperUser
> Add Contact.LastBoardTermStartDate

- force-app/main/default/objects/Contact/fields/AvailableAsTsimTA__c.field-meta.xml
- force-app/main/default/permissionsets/AtlasSuperUser.permissionset-meta.xml
- force-app/main/default/quickActions/Contact.TeamFacilitator.quickAction-meta.xml
- scratch-config/main/default/profiles/Admin.profile-meta.xml
1. Added Available as TSiM TA to Contact fields
2. Added to TeamFacilitator quick action
3. Added to AtlasSuperUser permission set
4. Added to Admin profile
> Added Available as TSiM TA

- force-app/main/default/lwc/ceuFormCmp/ceuFormCmp.html
- force-app/main/default/lwc/ceuFormCmp/ceuFormCmp.js
- force-app/main/default/lwc/editBackgroundCheckCmp/editBackgroundCheckCmp.html
- force-app/main/default/lwc/editCeuCmp/editCeuCmp.html
- force-app/main/default/lwc/editCeuCmp/editCeuCmp.js
- force-app/main/default/lwc/relatedBackgroundCheckCmp/relatedBackgroundCheckCmp.html
Fixed Cancel on New background check from related list.
Also fixed cancel on BackgroundCheck and CEU new button overrides.
#462
> Cancel buttons now redirect as expected

- force-app/main/default/triggers/ContactTrigger.trigger
Remove setting home email from email in trigger
> Remove setting home email from email

- force-app/main/default/permissionsets/AtlasSuperUser.permissionset-meta.xml
Added missing permission to Atlas Super User
> Add missing permission

- force-app/main/default/classes/TeamService.cls
- force-app/main/default/objects/DogRelationship__c/fields/Type__c.field-meta.xml
- force-app/main/default/permissionsets/AtlasSuperUser.permissionset-meta.xml
- force-app/main/test/TestTeamTrigger.cls
Should I make Type a required field?
Added check for null or blank type.
#475
> Fix problem with team trigger when Dog relationship without type exists

- datasets/beta/beta.dataset.sql
- datasets/beta/beta.extract.yml
- datasets/beta/beta.mapping.yml
- force-app/main/default/lwc/fileInformationCmp/fileInformationCmp.js
- force-app/main/test/TestContentDocumentLinkTrigger.cls
Add CategoryRule data to beta dataset
Fixed null reference exception when uploading files using the component with no document category and type defined.
#477
> Remove default values for category and type in lwc

- force-app/main/default/layouts/Contact-Atlas Contact Layout.layout-meta.xml
- force-app/main/default/objects/Contact/fields/EmailInclusion__c.field-meta.xml
- force-app/main/default/permissionsets/AtlasSuperUser.permissionset-meta.xml
Added EmailInclusion multi-select picklist to contact
#481
> Add EmailInclusion field to contact

- force-app/main/default/classes/PositionStatusController.cls
- force-app/main/default/lwc/relatedFilesCmp/relatedFilesCmp.css
- force-app/main/default/lwc/relatedFilesCmp/relatedFilesCmp.html
- force-app/main/default/lwc/relatedFilesCmp/relatedFilesCmp.js
1. Added pill container to show the file filters
2. Added handling of the delete pill to remove the filter
3. Fixed problem in PositionStatusController when date not defined
> 417 Make filtering more visible in file lists

- force-app/main/default/objects/Contact/fields/ClientFacilitatorAvailability__c.field-meta.xml
- force-app/main/default/permissionsets/AtlasSuperUser.permissionset-meta.xml
- force-app/main/default/permissionsets/AtlasTeam.permissionset-meta.xml
- force-app/main/default/quickActions/Contact.Client.quickAction-meta.xml
Added picklist field for Facilitator Availability
Added field to Client action
Added field to Atlas Super User and Atlas Team permission sets
> Add picklist field for Client Facilitator Availability

- force-app/main/default/objects/Contact/fields/LastBoardTermStartDate__c.field-meta.xml
Removed default from LastBoardTermStartDate
#518
> Remove default from LastBoardTermStartDate

- cumulusci.yml
- datasets/README.md
- force-app/main/default/classes/BackgroundCheckController.cls
- force-app/main/default/lwc/relatedBackgroundChecksCmp/relatedBackgroundChecksCmp.js
- force-app/main/default/lwc/relatedObjectCmp/relatedObjectCmp.js
- sfdx-project.json
Use package object to get namespace in redirect link
Add link to background check in related list.
#534, #527
> 534 redirect to all related

- force-app/main/default/classes/FileController.cls
- force-app/main/default/lwc/fileInformationCmp/fileInformationCmp.js
- force-app/main/default/lwc/fileUpdateCmp/fileUpdateCmp.js
- force-app/main/default/lwc/relatedFilesCmp/relatedFilesCmp.js
Add file type to columns in related files list, and to the file update dialog.
#569
> Show user file type

- force-app/main/default/classes/teams/TeamService.cls
- force-app/main/default/flexipages/DogRecordPage.flexipage-meta.xml
- force-app/main/default/layouts/Dog__c-Dog Layout.layout-meta.xml
- force-app/main/default/layouts/Team__c-Team Layout.layout-meta.xml
- force-app/main/default/objects/Dog__c/fields/XrayRequired__c.field-meta.xml
- force-app/main/default/objects/Team__c/fields/XrayRequired__c.field-meta.xml
- force-app/main/default/permissionsets/AtlasTeam.permissionset-meta.xml
- force-app/main/test/MockProvider.cls
- force-app/main/test/teams/TestTeamService.cls
- force-app/main/test/teams/TestTeamService.cls-meta.xml
1. Added X-ray required to team and dog
2. Added setting value in Dog based on team to team trigger
#557 #577
> Add X-ray required

- force-app/main/default/lwc/relatedCeusCmp/relatedCeusCmp.js
Added Program Title to related CEUs list
#606
> Add field to related list

- force-app/main/default/classes/certifications/CertificationRepository.cls
- force-app/main/default/classes/certifications/CertificationService.cls
- force-app/main/default/quickActions/Contact.TeamFacilitator.quickAction-meta.xml
- force-app/main/test/certifications/TestCertificationRepository.cls
Fix trigger error when updating CEUs that are in the wrong Certification.
#604
> Make sure trigger has all fields

- force-app/main/default/classes/certifications/CertificationRepository.cls
- force-app/main/default/classes/certifications/CertificationService.cls
- force-app/main/test/certifications/TestCertificationRepository.cls
- force-app/main/test/certifications/TestCertificationService.cls
1. Add check that a CEU is not assigned To another Cert of the same type before adding it.
#608
> Add check that CEU is not assigned
